name: Checks
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  spellchecking:
    name: Spellchecking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 200
    - uses: actions/checkout@v3
      with:
        repository: rust-lang-ru/common-configs
        path: common-configs
    - run: npm install yaspeller
    - run: git show -m --name-only -1 --format="format:" | grep --color=never -i '.md' | xargs node_modules/.bin/yaspeller -c common-configs/.yaspellerrc
  gitlocalize-bug-checking:
    name: Checking Gitlocalize bugs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 200
    - uses: rust-lang-ru/simpleinfra/gitocalize-bug-checker@master
    - uses: rust-lang-ru/simpleinfra/gl-bugs-checker@master
      if: ${{ github.event_name == 'pull_request' }}
      with:
        original_dir: rustbook-en/src
        translation_dir: rustbook-ru/src
